import type { NextPage } from 'next'
import Head from 'next/head'
import Experience from '../components/Experience/Experience'

import IntroHero from '../components/IntroHero/IntroHero'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Head>
        <title>Oliver Patrick (Dev) - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <IntroHero />
      <Experience />
    </div>
  )
}

export default Home
