name: Build and Release opdev.co.uk

on: 
  push:
    branches: main

jobs:
  build-deploy:
    name: Build Next.js Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v2
      - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16
      - name: Install NPM dependencies
        run: npm install
      - name: Build website
        run: npm run build